export const bellaRoomOffers = {
  "garden-family-room": {
    pricing: {
      basePrice: 2990000,
      currentPrice: 1196000,
      currency: "VND",
      unit: "night",
      taxesIncluded: true,
      discountPercent: 60,
    },
    bookingOptions: {
      breakfastAvailable: true,
      breakfastPrice: 100000,
      freeCancellation: false,
      cancellationText: "Phí hủy: 50% tiền phòng",
      payAtProperty: true,
      prepaymentRequired: false,
      geniusEligible: true,
      roomsLeft: 1,
    },
  },
  "balcony-twin-room": {
    pricing: {
      basePrice: 2500000,
      currentPrice: 1000000,
      currency: "VND",
      unit: "night",
      taxesIncluded: true,
      discountPercent: 60,
    },
    bookingOptions: {
      breakfastAvailable: true,
      breakfastPrice: 100000,
      freeCancellation: false,
      cancellationText: "Phí hủy: 50% tiền phòng",
      payAtProperty: true,
      prepaymentRequired: false,
      geniusEligible: true,
      roomsLeft: 1,
    },
  },
  "sea-view-double-or-twin-room": {
    pricing: {
      basePrice: 2400000,
      currentPrice: 960000,
      currency: "VND",
      unit: "night",
      taxesIncluded: true,
      discountPercent: 60,
    },
    bookingOptions: {
      breakfastAvailable: true,
      breakfastPrice: 100000,
      freeCancellation: false,
      cancellationText: "Phí hủy: 50% tiền phòng",
      payAtProperty: true,
      prepaymentRequired: false,
      geniusEligible: true,
      roomsLeft: 2,
    },
  },
  "sea-view-studio": {
    pricing: {
      basePrice: null,
      currentPrice: null,
      currency: "VND",
      unit: "night",
      taxesIncluded: null,
      discountPercent: null,
    },
    bookingOptions: {
      breakfastAvailable: null,
      breakfastPrice: null,
      freeCancellation: null,
      cancellationText: null,
      payAtProperty: null,
      prepaymentRequired: null,
      geniusEligible: null,
      roomsLeft: null,
    },
  },
  "side-sea-view-deluxe-double-room": {
    pricing: {
      basePrice: 2400000,
      currentPrice: 960000,
      currency: "VND",
      unit: "night",
      taxesIncluded: true,
      discountPercent: 60,
    },
    bookingOptions: {
      breakfastAvailable: true,
      breakfastPrice: 100000,
      freeCancellation: false,
      cancellationText: "Phí hủy: 50% tiền phòng",
      payAtProperty: true,
      prepaymentRequired: false,
      geniusEligible: true,
      roomsLeft: 3,
    },
  },
  "two-bedroom-sea-view-apartment": {
    pricing: {
      basePrice: 7600000,
      currentPrice: 3040000,
      currency: "VND",
      unit: "night",
      taxesIncluded: true,
      discountPercent: 60,
    },
    bookingOptions: {
      breakfastAvailable: true,
      breakfastPrice: 100000,
      freeCancellation: false,
      cancellationText: "Phí hủy: 50% tiền phòng",
      payAtProperty: true,
      prepaymentRequired: false,
      geniusEligible: true,
      roomsLeft: 1,
    },
  },
};
