export const bellaContent = {
  meta: {
    title: "Bella Hotel Phú Quốc | Đặt phòng trực tiếp",
    description:
      "Khám phá Bella Hotel Phú Quốc với các hạng phòng hướng biển, vị trí gần Sunset Town và quy trình đặt phòng trực tiếp, gọn gàng.",
  },
  property: {
    name: "BELLA HOTEL Phu Quoc",
    kicker: "Bella Hotel Phú Quốc",
    heroTitle: "Kỳ nghỉ nhẹ nhàng tại Bella Hotel Phú Quốc",
    heroCopy:
      "Lưu trú ngay khu Sunset Town với không gian sạch sẽ, hiện đại và thuận tiện để khám phá cáp treo, Kiss Bridge cùng bờ biển phía Nam của Phú Quốc.",
    shortDescription:
      "Khách sạn 3 sao tại An Thới với nhiều hạng phòng phù hợp cho cặp đôi, gia đình và nhóm bạn muốn nghỉ ngơi thoải mái gần các điểm đến nổi bật.",
    address:
      "SOR209 Khu do thi Sun Premier Village Primavera, To 10, Khu, Dac khu Phu Quoc, An Thoi, Phu Quoc, Viet Nam",
    city: "Phu Quoc",
    country: "Vietnam",
    distanceFromCenter: "Cách trung tâm Phú Quốc khoảng 22 km",
    locationCue:
      "Bella nằm trong khu Sun Premier Village Primavera, phù hợp cho du khách muốn ở gần Sunset Town, khu cáp treo và các điểm tham quan ven biển phía Nam đảo.",
    overviewPoints: [
      "Nhiều khách nhắc đến phòng mới, sạch sẽ và không gian lưu trú gọn gàng, dễ chịu.",
      "Danh mục phòng đa dạng từ phòng tiêu chuẩn, studio đến căn hộ 2 phòng ngủ cho nhóm đông người.",
      "Theo thông tin khách sạn, Bella có Wi-Fi miễn phí, quầy hỗ trợ 24 giờ và quy trình nhận, trả phòng nhanh.",
    ],
    trustStrip: [
      {
        title: "Điểm đánh giá tốt từ khách lưu trú",
        copy: "Điểm tổng thể 8,6/10 với vị trí được chấm 9,2/10.",
      },
      {
        title: "Wi-Fi miễn phí toàn khách sạn",
        copy: "Phù hợp cho kỳ nghỉ ngắn ngày và giữ kết nối ổn định khi cần.",
      },
      {
        title: "Nhận và trả phòng nhanh",
        copy: "Quy trình lưu trú gọn gàng, dễ theo dõi trên website.",
      },
      {
        title: "Gần các điểm tham quan phía Nam đảo",
        copy: "Thuận tiện đi Sunset Town, khu cáp treo và các điểm ven biển.",
      },
    ],
    finalCtaTitle: "Sẵn sàng chọn hạng phòng phù hợp cho kỳ nghỉ tại Phú Quốc?",
    finalCtaCopy:
      "Xem chi tiết từng hạng phòng, kiểm tra giá hiện tại và hoàn tất đặt phòng trực tiếp tại Bella Hotel Phú Quốc.",
  },
  trust: {
    guestScore: 8.6,
    displayedScore: 8.5,
    reviewCount: 104,
    displayedReviewCount: 103,
    locationScore: 9.2,
    breakfastScore: 10,
    starRating: 3,
    languages: ["English", "Vietnamese"],
  },
  gallery: [
    {
      src: "/bella/bella-hero.jpg",
      alt: "Khung cảnh ven biển gần Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-exterior.jpg",
      alt: "Mặt ngoài Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-arrival.jpg",
      alt: "Không gian đón khách tại Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-seafront.jpg",
      alt: "Bờ biển gần Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-room-detail.jpg",
      alt: "Chi tiết phòng nghỉ tại Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-room-beds.jpg",
      alt: "Bố trí giường ngủ tại Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-layout.jpg",
      alt: "Không gian bên trong Bella Hotel Phú Quốc",
    },
    {
      src: "/bella/bella-family.jpg",
      alt: "Bố cục phòng gia đình tại Bella Hotel Phú Quốc",
    },
  ],
  amenityGroups: [
    {
      title: "Tiện nghi được quan tâm",
      items: [
        "Wi-Fi miễn phí",
        "Xe đưa đón sân bay",
        "Phòng gia đình",
        "Phòng không hút thuốc",
        "Chỗ đỗ xe miễn phí",
        "Dịch vụ phòng",
      ],
    },
    {
      title: "Dịch vụ lưu trú cơ bản",
      items: [
        "Quầy lễ tân 24 giờ",
        "Điều hòa",
        "Khu BBQ",
        "Khu vườn nhỏ",
        "Sảnh sinh hoạt chung",
        "Nhận và trả phòng nhanh",
      ],
    },
    {
      title: "Cảm giác nghỉ ngơi thoải mái",
      items: [
        "Phòng tắm riêng",
        "TV màn hình phẳng",
        "Cách âm",
        "Nhiều lựa chọn tầm nhìn",
        "Khu vực picnic",
        "Tủ quần áo và két an toàn",
      ],
    },
  ],
  breakfast: {
    score: "Điểm bữa sáng 10/10 từ khách lưu trú",
    options: [
      "Kiểu Ý",
      "Full English / Irish",
      "Chay",
      "Thuần chay",
      "Halal",
      "Kiểu Á",
      "Gọi món",
    ],
  },
  nearbyPlaces: [
    {
      name: "Sunset Town và Kiss Bridge",
      distance: "Khách lưu trú đánh giá là thuận tiện để di chuyển",
    },
    {
      name: "Khu cáp treo",
      distance: "Rất gần theo phản hồi của khách",
    },
    {
      name: "Kids Club",
      distance: "2.5 km",
    },
    {
      name: "Bờ biển Phú Quốc",
      distance: "Không gian ven biển ở khu vực lân cận",
    },
  ],
  policies: {
    checkIn: [
      "Nhận phòng từ 14:00 đến 00:00.",
      "Khách được yêu cầu xuất trình giấy tờ tùy thân có ảnh và thẻ tín dụng khi đến nơi.",
      "Bella đề nghị khách thông báo giờ đến trước nếu có thể.",
    ],
    checkOut: [
      "Trả phòng trước 00:00.",
      "Các yêu cầu đặc biệt phụ thuộc vào tình trạng thực tế và có thể phát sinh phụ phí.",
    ],
    houseRules: [
      "Không cho phép vật nuôi.",
      "Không có yêu cầu tối thiểu về độ tuổi nhận phòng.",
      "Đặt từ 3 phòng trở lên có thể áp dụng chính sách nhóm riêng.",
    ],
    paymentMethodsAtProperty: [
      "American Express",
      "Visa",
      "Mastercard",
      "JCB",
      "Cash",
    ],
  },
  reviewHighlights: [
    {
      quote:
        "Khách lưu trú đánh giá cao phòng mới, sạch sẽ và cảm giác nghỉ ngơi thoải mái khi ở Bella.",
      source: "Tóm tắt phản hồi từ khách lưu trú thực tế",
    },
    {
      quote:
        "Vị trí thuận tiện gần Sunset Town cùng sự hỗ trợ nhiệt tình từ chủ khách sạn là điểm được nhắc lại nhiều lần.",
      source: "Điểm nổi bật từ nhóm khách đôi và nhóm bạn",
    },
    {
      quote:
        "Bella phù hợp cho hành trình nghỉ ngắn ngày nhờ dễ di chuyển tới khu cáp treo, Kiss Bridge và các điểm ven biển.",
      source: "Tóm tắt đánh giá về vị trí",
    },
  ],
  rooms: [
    {
      code: "garden-family-room",
      name: {
        vi: "Phòng Gia đình Nhìn ra Vườn",
        en: null,
      },
      category: "room",
      summary: "1 phòng, 30m², 1 giường đơn, 1 giường đôi lớn, nhìn ra vườn, núi và thành phố.",
      areaSqm: 30,
      bedroomCount: 1,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [
        { type: "single", quantity: 1, label: "1 giường đơn" },
        { type: "queen", quantity: 1, label: "1 giường đôi lớn" },
      ],
      spaces: ["bedroom"],
      views: ["garden", "mountain", "city"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "safe",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "fan",
        "electric_kettle",
        "wardrobe",
        "clothes_rack",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Phòng Gia đình Nhìn ra Vườn",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: ["Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này."],
      images: ["/bella/bella-family.jpg", "/bella/bella-layout.jpg"],
    },
    {
      code: "balcony-twin-room",
      name: {
        vi: "Phòng 2 giường đơn có ban công",
        en: null,
      },
      category: "room",
      summary: "1 phòng, 30m², 2 giường đơn, có ban công và nhìn ra vườn, thành phố, núi.",
      areaSqm: 30,
      bedroomCount: 1,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [{ type: "single", quantity: 2, label: "2 giường đơn" }],
      spaces: ["bedroom", "balcony"],
      views: ["garden", "city", "mountain"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "safe",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "electric_kettle",
        "wardrobe",
        "clothes_rack",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Phòng 2 giường đơn có ban công",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: ["Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này."],
      images: ["/bella/bella-room-beds.jpg", "/bella/bella-room-detail.jpg"],
    },
    {
      code: "sea-view-double-or-twin-room",
      name: {
        vi: "Phòng giường đôi/2 giường đơn nhìn ra biển",
        en: null,
      },
      category: "room",
      summary: "1 phòng, 30m², 2 giường đơn hoặc 1 giường đôi cực lớn, nhìn ra biển, vườn và thành phố.",
      areaSqm: 30,
      bedroomCount: 1,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [
        { type: "single", quantity: 2, label: "2 giường đơn" },
        { type: "extra_large_double", quantity: 1, label: "1 giường đôi cực lớn" },
      ],
      spaces: ["bedroom"],
      views: ["sea", "garden", "city"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "safe",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "fan",
        "electric_kettle",
        "wardrobe",
        "clothes_rack",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Phòng giường đôi/2 giường đơn nhìn ra biển",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: [
        "Thông tin hướng biển được giữ theo tên hạng phòng; phần mô tả chi tiết không lặp lại rõ nội dung này.",
        "Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này.",
      ],
      images: ["/bella/bella-seafront.jpg", "/bella/bella-room-detail.jpg"],
    },
    {
      code: "sea-view-studio",
      name: {
        vi: "Studio nhìn ra biển",
        en: null,
      },
      category: "studio",
      summary: "1 studio nguyên căn, 28m², 1 giường đôi lớn, có bếp nhỏ riêng và nhìn ra biển.",
      areaSqm: 28,
      bedroomCount: 0,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [{ type: "queen", quantity: 1, label: "1 giường đôi lớn" }],
      spaces: ["bedroom", "kitchen"],
      views: ["sea"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "safe",
        "sofa",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "microwave",
        "kitchenette",
        "kitchenware",
        "fan",
        "electric_kettle",
        "wardrobe",
        "clothes_rack",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Studio nhìn ra biển",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: ["Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này."],
      images: ["/bella/bella-layout.jpg", "/bella/bella-seafront.jpg"],
    },
    {
      code: "side-sea-view-deluxe-double-room",
      name: {
        vi: "Phòng Deluxe giường đôi nhìn ra biển từ phía bên cạnh",
        en: null,
      },
      category: "room",
      summary: "1 phòng, 28m², 1 giường đôi lớn, nhìn ra biển từ phía bên cạnh và ra khung cảnh.",
      areaSqm: 28,
      bedroomCount: 1,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [{ type: "queen", quantity: 1, label: "1 giường đôi lớn" }],
      spaces: ["bedroom"],
      views: ["side_sea", "landmark"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "safe",
        "sofa",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "fan",
        "electric_kettle",
        "wardrobe",
        "clothes_rack",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Phòng Deluxe giường đôi nhìn ra biển từ phía bên cạnh",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: [
        "Thông tin hướng biển một phần được giữ theo tên hạng phòng; phần mô tả chi tiết chỉ nêu tầm nhìn ra khung cảnh.",
        "Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này.",
      ],
      images: ["/bella/bella-arrival.jpg", "/bella/bella-room-beds.jpg"],
    },
    {
      code: "two-bedroom-sea-view-apartment",
      name: {
        vi: "Căn hộ 2 phòng ngủ nhìn ra biển",
        en: null,
      },
      category: "apartment",
      summary: "1 căn hộ nguyên căn, 96m², 2 phòng ngủ, phòng khách có 2 giường sofa, có bếp riêng, ban công, nhìn ra biển và núi.",
      areaSqm: 96,
      bedroomCount: 2,
      bathroomCount: 1,
      maxAdults: null,
      maxChildren: null,
      maxOccupancy: null,
      bedConfigs: [
        { type: "single", quantity: 2, label: "Phòng ngủ 1: 2 giường đơn" },
        {
          type: "extra_large_double",
          quantity: 1,
          label: "Phòng ngủ 2: 1 giường đôi cực lớn",
        },
        { type: "sofa_bed", quantity: 2, label: "Phòng khách: 2 giường sofa" },
      ],
      spaces: ["bedroom", "living_room", "kitchen", "balcony"],
      views: ["sea", "mountain"],
      bathroomFeatures: [
        "private_bathroom",
        "free_toiletries",
        "towels",
        "bidet",
        "slippers",
        "toilet",
        "hairdryer",
        "toilet_paper",
        "bath_or_shower",
      ],
      amenities: [
        "air_conditioning",
        "kitchen",
        "safe",
        "sofa",
        "socket_near_bed",
        "cleaning_products",
        "hypoallergenic",
        "tile_marble_floor",
        "desk",
        "seating_area",
        "soundproof",
        "tv",
        "refrigerator",
        "telephone",
        "pay_tv",
        "flat_screen_tv",
        "microwave",
        "kitchenette",
        "kitchenware",
        "fan",
        "electric_kettle",
        "wardrobe",
        "dining_area",
        "dining_table",
        "clothes_rack",
        "interconnected_room",
        "carbon_monoxide_detector",
        "individual_ac",
        "hand_sanitizer",
      ],
      accessibility: {
        accessModes: ["elevator", "stairs"],
        accessNote:
          "Các phòng trong cùng hạng có thể được tiếp cận bằng thang máy hoặc cầu thang tùy vị trí thực tế.",
      },
      policies: { smoking: "non_smoking" },
      rawSourceName: "Căn hộ 2 phòng ngủ nhìn ra biển",
      source: { type: "docx", file: "TienIch.docx" },
      dataWarnings: [
        "Tài liệu nguồn không nêu rõ số phòng tắm; hệ thống đang giữ mặc định an toàn là 1.",
        "Tài liệu nguồn không nêu rõ sức chứa chuẩn hóa của hạng phòng này.",
      ],
      images: ["/bella/bella-exterior.jpg", "/bella/bella-seafront.jpg"],
    },
  ],
};
