import { Combo } from "../config/database.js";

const DEFAULT_BELLA_COMBOS = [
  {
    name: "Chill Nhẹ",
    slug: "chill-nhe",
    description: "Gói nghỉ nhanh 2N1Đ cho cặp đôi muốn đổi gió tại Phú Quốc với phòng Double và xe máy nửa ngày.",
    room_types_allowed: ["double", "sea-view-double-or-twin-room", "side-sea-view-deluxe-double-room"],
    duration_label: "2N1Đ",
    nights: 1,
    allowed_nights: [1],
    days: 2,
    min_guests: 2,
    max_guests: 2,
    base_price: 899000,
    price_type: "fixed",
    currency: "VND",
    included_services: ["Phòng", "Nước suối", "Minibar cơ bản", "Check-in sớm", "Thuê xe máy 1 buổi"],
    suitable_for: "Cặp đôi, nghỉ nhanh",
    badge_label: "Best Seller",
    image_url: "/bella/sea-view-double-or-twin-room/sea-view-double-or-twin-room-01.jpg",
    icon_key: "sparkles",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: ["Áp dụng theo tình trạng phòng trống.", "Check-in sớm cần được Bella xác nhận trước."],
    display_order: 1,
  },
  {
    name: "Năng Động Khám Phá",
    slug: "nang-dong-kham-pha",
    description: "Gói trải nghiệm Nam đảo cho 2 khách, kết hợp lưu trú, tour, lặn san hô và di chuyển thuận tiện.",
    room_types_allowed: ["double", "sea-view-double-or-twin-room", "side-sea-view-deluxe-double-room"],
    duration_label: "2N1Đ",
    nights: 1,
    allowed_nights: [1],
    days: 2,
    min_guests: 2,
    max_guests: 2,
    base_price: 1290000,
    price_type: "fixed",
    currency: "VND",
    included_services: ["Phòng", "Tour Nam Đảo", "Lặn san hô", "Xe máy 1 ngày", "Đưa đón sân bay 1 chiều"],
    suitable_for: "Gen Z, thích trải nghiệm",
    badge_label: "Hot Deal",
    image_url: "/bella/bella-seafront.jpg",
    icon_key: "compass",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: ["Lịch tour phụ thuộc thời tiết.", "Vui lòng cung cấp giờ bay khi cần đưa đón."],
    display_order: 2,
  },
  {
    name: "Công Tác Hết Mình",
    slug: "cong-tac-het-minh",
    description: "Gói 2N1Đ cho nhóm 3-4 khách cần phòng Business, bữa BBQ và phương tiện di chuyển trong ngày.",
    room_types_allowed: ["business", "studio", "sea-view-studio"],
    duration_label: "2N1Đ",
    nights: 1,
    allowed_nights: [1],
    days: 2,
    min_guests: 3,
    max_guests: 4,
    base_price: 1590000,
    price_type: "fixed",
    currency: "VND",
    included_services: ["Phòng", "BBQ tối", "2 xe máy/ngày", "Trái cây", "Nước"],
    suitable_for: "Nhóm bạn hoặc nhóm công tác",
    badge_label: "Team Pick",
    image_url: "/bella/sea-view-studio/sea-view-studio-01.jpg",
    icon_key: "briefcase",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: ["BBQ cần đặt trước tối thiểu 24 giờ.", "Số lượng xe tùy theo tình trạng thực tế."],
    display_order: 3,
  },
  {
    name: "Gia Đình Thảnh Thơi",
    slug: "gia-dinh-thanh-thoi",
    description: "Gói gia đình 2N1Đ với phòng Family 2PN, đưa đón sân bay hai chiều và bữa sáng cho 4 người.",
    room_types_allowed: ["family", "family-2pn", "garden-family-room", "two-bedroom-sea-view-apartment"],
    duration_label: "2N1Đ",
    nights: 1,
    allowed_nights: [1],
    days: 2,
    min_guests: 3,
    max_guests: 4,
    base_price: 2490000,
    price_type: "fixed",
    currency: "VND",
    included_services: ["Phòng", "Đưa đón sân bay 2 chiều", "Ăn sáng 4 người", "Trái cây", "Hỗ trợ tour"],
    suitable_for: "Gia đình",
    badge_label: "Family Pick",
    image_url: "/bella/garden-family-room/garden-family-room-01.jpg",
    icon_key: "family",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: ["Bữa sáng áp dụng tối đa 4 người.", "Đưa đón sân bay cần xác nhận lịch trước."],
    display_order: 4,
  },
  {
    name: "Stay & Relax",
    slug: "stay-and-relax",
    description: "Gói 3N2Đ dành cho kỳ nghỉ dài hơn, kèm bữa tối, xe máy 2 ngày, giặt ủi và late check-out.",
    room_types_allowed: ["double", "triple", "sea-view-double-or-twin-room", "side-sea-view-deluxe-double-room"],
    duration_label: "3N2Đ",
    nights: 2,
    allowed_nights: [2],
    days: 3,
    min_guests: 2,
    max_guests: 3,
    base_price: 1990000,
    price_type: "from_price",
    currency: "VND",
    included_services: ["2 đêm", "1 bữa tối", "Xe máy 2 ngày", "Giặt ủi", "Late check-out"],
    suitable_for: "Nghỉ dưỡng dài ngày",
    badge_label: "Relax Choice",
    image_url: "/bella/bella-room-detail.jpg",
    icon_key: "waves",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: ["Giá từ tùy hạng phòng thực tế.", "Late check-out phụ thuộc công suất phòng."],
    display_order: 5,
  },
  {
    name: "All-in Phú Quốc",
    slug: "all-in-phu-quoc",
    description: "Gói trọn gói lưu trú, tour 4 đảo, cáp treo, ăn uống, xe và đưa đón sân bay cho hành trình gọn nhẹ.",
    room_types_allowed: ["linh hoạt"],
    duration_label: "2N1Đ hoặc 3N2Đ",
    nights: 1,
    allowed_nights: [1, 2],
    days: 2,
    min_guests: 1,
    max_guests: null,
    base_price: 2990000,
    price_type: "per_person",
    currency: "VND",
    included_services: ["Lưu trú", "Tour 4 đảo", "Cáp treo", "Ăn uống", "Xe", "Đưa đón sân bay"],
    suitable_for: "Trọn gói",
    badge_label: "All-in",
    image_url: "/bella/bella-exterior.jpg",
    icon_key: "map",
    is_active: true,
    valid_from: new Date("2026-01-01T00:00:00.000Z"),
    valid_to: new Date("2026-12-31T23:59:59.999Z"),
    terms_and_conditions: [
      "Giá hiển thị theo người, từ 2.990.000 VNĐ.",
      "Gói 3N2Đ có thể điều chỉnh theo lịch trình thực tế.",
    ],
    display_order: 6,
  },
];

export async function seedDefaultCombosIfEmpty() {
  const comboCount = await Combo.countDocuments();
  if (comboCount > 0) {
    return { inserted: 0, skipped: true };
  }

  try {
    const insertedCombos = await Combo.insertMany(DEFAULT_BELLA_COMBOS, { ordered: false });
    return { inserted: insertedCombos.length, skipped: false };
  } catch (error) {
    if (error.code === 11000) {
      return { inserted: 0, skipped: true };
    }
    throw error;
  }
}
